version: "3"

services:
  mcpo:
    build: .
    #image: ghcr.io/open-webui/mcpo:main
    #ports:
    #  - "8000:8000"
    volumes:
      - ./:/root/apps/mcp-collections
      - ../reddit_mcp_server_go:/root/apps/reddit_mcp_server_go
    working_dir: /root/apps/mcp-collections/
    command: --config mcp_config.json
    restart: always
    networks:
      - nginxmanager_default

networks:
  nginxmanager_default:
    external: true
